-- SQL to set up the EduAttend database in Supabase
-- Run this in the Supabase SQL Editor

-- Enable the uuid-ossp extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 0. Clean slate (Optional: Remove if you want to keep existing data)
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 1. Create Profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT,
  role TEXT CHECK (role IN ('student', 'faculty')) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Attendance table
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID NOT NULL,
  faculty_id UUID NOT NULL,
  subject TEXT NOT NULL,
  status TEXT CHECK (status IN ('Present', 'Absent', 'Late')) DEFAULT 'Present',
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT attendance_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
  CONSTRAINT attendance_faculty_id_fkey FOREIGN KEY (faculty_id) REFERENCES public.profiles(id) ON DELETE CASCADE
);

-- 3. Set up Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

-- Simple Policy: Anyone with the anon key can read (for demo purposes)
DROP POLICY IF EXISTS "Public Read Access" ON public.profiles;
CREATE POLICY "Public Read Access" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access" ON public.attendance;
CREATE POLICY "Public Read Access" ON public.attendance FOR SELECT USING (true);

DROP POLICY IF EXISTS "Any Insert Access" ON public.profiles;
CREATE POLICY "Any Insert Access" ON public.profiles FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Faculty Insert Access" ON public.attendance;
CREATE POLICY "Faculty Insert Access" ON public.attendance FOR INSERT WITH CHECK (true);
